config/routes.rb
Rails.application.routes.draw do
  resources :passages, only: [:index, :create]
  resources :genres, only: [:show]

  get '/songs/search_song' => 'songs#search_song'
  get '/songs/best_song_match'
  get '/lyrics/search_lyrics'
  root to: "passages#index"

  resources :songs, only: [:show]
end

app/models/song.rb
class Song < ActiveRecord::Base
  scope :recent, -> { order("created_at DESC").limit(5) }
  validates :artist_name, :song_title, presence: true

  has_one   :lyric
  belongs_to   :genre

  def self.most_recent_with_lyrics
    Song.recent.select do |song|
      song.genre.has_lyrics
    end
  end

  def self.song_ids
    song_ids = []
    Song.recent.each do |song|
      song_ids.push(song.id)
    end
    song_ids
  end

  def self.match_lyric_to_song(recent_lyrics)
    song_lyric_matches = []
    recent_lyrics.each do |lyric_object|
      if Song.song_ids.include?(lyric_object.song_id)
        song_lyric_matches.push(lyric_object)
      end
    end
    song_lyric_matches
  end

  def self.strongest_emotion_matches(song_lyric_matches)
    emotion_object_matches = []

    song_lyric_matches.each do |lyric_object|
      emotions = Emotion.where(emotionable_id: lyric_object.id)
      emotions.each do |emotion|
        emotion_object_matches.push(emotion)
      end
    end

    emotion_object_matches
  end

  def self.chosen_song
    final_lyric = nil
    final_song = nil

    if Song.most_recent_with_lyrics.length == 0
      final_song = Song.recent.offset(rand(Song.recent.count)).first
    elsif Song.most_recent_with_lyrics.length >= 1
      lyrics = Lyric.recent
      song_lyric_matches = Song.match_lyric_to_song(lyrics)
      emotion_object_matches = Song.strongest_emotion_matches(song_lyric_matches)

      values = Emotion.strongest_matches(emotion_object_matches)
      final_value = Emotion.compare_matches(values)

      strongest_passage_emotion = Passage.last.emotion.strongest_emotion
      strongest_passage_emotion

      emotion_object_matches.each do |emotion_object|
        if emotion_object.read_attribute(strongest_passage_emotion) == final_value
          final_lyric = Lyric.find_by(id: emotion_object.emotionable_id)
          final_song = final_lyric.song
        end
      end
    end
    final_song
  end

  def map_emotions(primary_emotion)
    case primary_emotion
    when "Anger"
      {min_valence: 0.3, max_valence: 0.6, min_energy: 0.7}
    when "Disgust"
      {min_valence: 0.3, max_valence: 0.7, min_energy: 0.6, max_acousticness: 0.2}
    when "Fear"
      {min_valence: 0.3, max_valence: 0.7, min_energy: 0.5, max_acousticness: 0.2}
    when "Joy"
      {min_valence: 0.7}
    when "Sadness"
      {max_valence: 0.3}
    end
  end

  def get_recommendations(genre_hash, primary_emotion)
    authenticate = RSpotify.authenticate(ENV['SPOTIFY_CLIENT_ID'], ENV["SPOTIFY_CLIENT_SECRET"])
    RSpotify.raw_response = true

    options_hash = map_emotions(primary_emotion)
    options_hash[:limit] = 5
    options_hash[:seed_genres] = genre_hash[:seed_genres]
    recommendations = RSpotify::Recommendations.generate(options_hash)

    JSON.parse(recommendations)
  end

  def parse_recommendations(recommendations)
    metadata_list = []
    recommendations["tracks"].each do |track|
      metadata_list << {"artist" => track["artists"][0]["name"], "track" => track["name"], "uri" => track["uri"]}
    end
    metadata_list
  end


end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def search_song
    genre_id = params[:genre_id].to_i
    genre = Genre.find_by(id: genre_id)

    emotion = Passage.last.emotion.strongest_emotion.capitalize!

    @song = Song.new
    recommendations = @song.get_recommendations({ seed_genres: genre.categories }, emotion)
    parsed = @song.parse_recommendations(recommendations)

    parsed.each do |song|
      Song.create(artist_name: song["artist"], song_title: song["track"], uri: song["uri"], genre_id: genre.id)
    end

    has_lyrics = Song.most_recent_with_lyrics

    if has_lyrics.length > 1
      redirect_to lyrics_search_lyrics_path
    else
      redirect_to songs_best_song_match_path
    end
  end

  def best_song_match
    best_song_match = Song.chosen_song
    best_song_match.update_attributes(chosen_song: true)
    redirect_to "/songs/show"
  end

  def show
    @passage = Passage.last
    @passage_emotion = Emotion.find_by(emotionable_id: @passage.id, emotionable_type: "Passage")
    @strongest_emotion_from_passage = @passage.emotion.strongest_emotion
    @strongest_emotion_passage_score = (@passage.emotion.read_attribute(@strongest_emotion_from_passage).to_f * 100).to_i
    @the_one_uri = Song.chosen_song.uri

    if Song.chosen_song.genre.has_lyrics
      lyric = Song.chosen_song.lyric
      @lyrics_emotion = Emotion.find_by(emotionable_id: lyric.id)
      @strongest_emotion_from_lyrics = lyric.emotion.strongest_emotion
      @strongest_emotion_lyrics_score = (lyric.emotion.read_attribute(@strongest_emotion_from_lyrics).to_f * 100).to_i
    end
  end
end

app/helpers/song_helper.rb
module SongHelper
end

app/views/songs/show.html.erb
<div class="center">
  <div class="song">
      <h1>We hope you enjoy the song we chose for you.</h1>
      <center>
      <iframe src="https://embed.spotify.com/?uri=<%= @the_one_uri %>" width="500" height="80" frameborder="0" allowtransparency="true"></iframe>
      </center>
  </div>
  <div class="results">
    <h1>Insights from the Emotional Data</h1>

    <%= content_tag :div, class: "emotion-passage", data: {passage_emotion: @passage_emotion, strongest_emotion_from_passage: @strongest_emotion_from_passage
    } do %>
      <h2>From Your Passage</h2>
        Based on our calcuations, your text's strongest emotion detected was <%= @strongest_emotion_from_passage %>, which makes up <%= @strongest_emotion_passage_score %>% of the overall emotional scores.

        <h1>Text Emotion: <%= @strongest_emotion_from_passage %></h1>
        <h1>Score: <%= @strongest_emotion_passage_score %>%</h1>
    <% end %>
    <BR>
    <%= content_tag :div, class: "emotion-lyrics", data: {lyrics_emotion: @lyrics_emotion, strongest_emotion_from_lyrics: @strongest_emotion_from_lyrics, strongest_emotion_lyrics_score: @strongest_emotion_lyrics_score
    } do %>

      <% if @lyrics_emotion %>
      <h2>About the Song</h2>
      The song we have chosen for you is solely based on the data above.
          By analyzing the emotional tones detected within your text, the overall scores have been categorized by 5 emotions: Joy, Sadness, Anger, Disgust, and Fear.
          <p>
          <h1>
          Song Emotion: <%= @strongest_emotion_from_lyrics %></h1>
          
          <h1>Score: <%= @strongest_emotion_lyrics_score %>%</h1>
      <% end %>
    <% end %>
</div>

    <div class="color-legend">
      <h2>Color Legend</h2>
      <ul class="colors">
        <li id="joy">Joy</li>
        <li id="sadness">Sadness</li>
        <li id="anger">Anger</li>
        <li id="disgust">Disgust</li>
        <li id="fear">Fear</li>
      </ul>
    </div>
  </div>

  <center>
    <%= link_to 'Back to Home', passages_path %>
  </center>

  <footer class="animated fadeInUp">
      created by <a href="http://www.github.com/sayamkim" target="_blank">Sayam Kim</a>, <a href="http://www.github.com/kerianngannon" target="_blank">Keri Gannon</a>, <a href="http://www.github.com/jsgarrett1" target="_blank">Joel Garrett</a>, & <a href="http://www.github.com/omgannie" target="_blank">Annie Oh</a>
  </footer>